version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
  pre_build:
    commands:
      - echo install dependencies
      - npm install -g @angular/cli
      - cd src/main/client
      - ls
      - npm install
      - cd ..
      - cd ..
      - cd ..
    build:
      commands:
        - echo building application
        - mvn install
    post_build:
      commands:
        - mv target/monsters-0.0.1-SNAPSHOT.jar monsters-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - monsters-0.0.1-SNAPSHOT.jar